use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :gigalixir_phoenix, GigalixirPhoenixWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4000],
  url: [host: System.get_env("APP_NAME") <> ".gigalixirapp.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: Map.fetch!(System.get_env(), "SECRET_KEY_BASE"),
  server: true

# Do not print debug messages in production
config :logger, level: :info

config :gigalixir_phoenix, GigalixirPhoenix.Repo,
  url: System.get_env("DATABASE_URL"),
  ssl: true,
  pool_size: 2
